sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t daus2936/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true daus2936/docker-react npm run test -- --coverage
